CREATE OR REPLACE VIEW vpr_PRODUTO AS (

SELECT DISTINCT QP.SEQPRODUTO, QP.SEQFAMILIA, QP.PRODUTO DESCRICAO, QC.COMPRADOR_CADASTRO COMPRADOR,
       QP.SEQFORNECEDOR_PRINCIPAL CODFORNEC, QP.FORNECEDOR_PRINCIPAL FORNECEDOR,
       DPC.CODACESSO EAN, 
       CASE WHEN QP.SEQPRODUTO IN (SELECT DISTINCT SEQPRODUTO FROM DIM_PRODUTOEMPRESA QPR WHERE QPR.STATUSVENDA = 'A') THEN 'Ativo' ELSE 'Inativo' END STATUS_VDA,
       /* Quando o produto estiver ativo em qualquer empresa constará como 'ATIVO' */
       DP2.QTDEMBALAGEM QTDEMB,
       
       'NIVEL_1' NIVEL_1, QC.CATEGORIA_NIVEL_1, 
       'NIVEL_2' NIVEL_2, QC.CATEGORIA_NIVEL_2, 
       'NIVEL_3' NIVEL_3, QC.CATEGORIA_NIVEL_3, 
       'NIVEL_4' NIVEL_4, QC.CATEGORIA_NIVEL_4, 
       'NIVEL_5' NIVEL_5, QC.CATEGORIA_NIVEL_5, 
       
       CASE WHEN UPPER(QP.MARCA) LIKE '%NAGUMO%' THEN '1' 
            WHEN UPPER(QP.MARCA) LIKE 'PADARIA%' THEN '1'
            WHEN UPPER(QP.MARCA) LIKE 'ROTISSERIA%' THEN '1' ELSE '0' END MARCA_PROPRIA

FROM QLV_PRODUTO QP LEFT JOIN DIM_PRODUTOCODIGO DPC ON QP.SEQPRODUTO = DPC.SEQPRODUTO AND DPC.QTDEMBALAGEM = 1 AND DPC.TIPCODIGO = 'E' /*EAN*/
                    LEFT JOIN DIM_PRODUTOCODIGO DP2 ON QP.SEQPRODUTO = DP2.SEQPRODUTO AND DP2.STATUS = 'A'
                    LEFT JOIN QLV_CATEGORIA     QC  ON QP.SEQFAMILIA = QC.SEQFAMILIA
                    LEFT JOIN DIM_FORNECEDOR    DFR ON QP.SEQFORNECEDOR_PRINCIPAL = DFR.SEQFORNECEDOR

      /* WHERE QP.SEQPRODUTO IN(5500, 5173,594554) */
       
ORDER BY 1 ASC

);
