CREATE OR REPLACE VIEW NAGV_PM_PRODUTOS AS
SELECT QP.SEQPRODUTO PRODUTO_SKU,
             QP.SEQFAMILIA PRODUTO_FAMILIA,
             SM.SEQSIMILARIDADE,
             QP.PRODUTO PRODUTO_DESCRICAO,
             QC.COMPRADOR_CADASTRO PRODUTO_COMPRADOR,
             QP.SEQFORNECEDOR_PRINCIPAL PRODUTO_COD_FORNEC,
             QP.FORNECEDOR_PRINCIPAL PRODUTO_FORNECEDOR,
             QC.seqcategoria_nivel_1 PRODUTO_COD_NVL_01,
             QC.CATEGORIA_NIVEL_1 PRODUTO_NIVEL_01,
             QC.seqcategoria_nivel_2 PRODUTO_COD_NVL_02,
             QC.CATEGORIA_NIVEL_2 PRODUTO_NIVEL_02,
             QC.seqcategoria_nivel_3 PRODUTO_COD_NVL_03,
             QC.CATEGORIA_NIVEL_3 PRODUTO_NIVEL_03,
             QC.seqcategoria_nivel_4 PRODUTO_COD_NVL_04,
             QC.CATEGORIA_NIVEL_4 PRODUTO_NIVEL_04,
             QC.seqcategoria_nivel_5 PRODUTO_COD_NVL_05,
              QC.CATEGORIA_NIVEL_5 PRODUTO_NIVEL_05,
               fBuscaEANProdutomaior(QP.seqproduto) PRODUTO_EAN,
              /* Empresa Base loja 008 maior mix da rede*/
             CASE WHEN QP.SEQPRODUTO IN (SELECT DISTINCT SEQPRODUTO FROM DIM_PRODUTOEMPRESA QPR WHERE QPR.STATUSVENDA = 'A' AND QPR.NROEMPRESA = 8 ) THEN 'Ativo' ELSE 'Inativo' END PRODUTO_STATUS_VENDA,
             NULL PRODUTO_DATA_SAIDA,
             fBuscaembvenda(qp.seqproduto) PRODUTO_UNIDADE,
             NULL PRODUTO_TIPO
            --- CASE WHEN UPPER(QP.MARCA) in ( '%NAGUMO%' THEN '1' WHEN UPPER(QP.MARCA) LIKE 'PADARIA%' THEN '1'  WHEN UPPER(QP.MARCA) LIKE 'ROTISSERIA%' THEN '1' ELSE '0' END MARCA_PROPRIA --- Avaliar com Price

FROM QLV_PRODUTO QP  LEFT JOIN QLV_CATEGORIA     QC  ON QP.SEQFAMILIA = QC.SEQFAMILIA
                                              LEFT JOIN DIM_FORNECEDOR    DFR ON QP.SEQFORNECEDOR_PRINCIPAL = DFR.SEQFORNECEDOR
                                              LEFT JOIN (SELECT SM.* FROM DIM_PRODSIMILAR SM LEFT JOIN DIM_SIMILARIDADE MS ON SM.SEQSIMILARIDADE = MS.SEQSIMILARIDADE WHERE MS.TIPOSIMILARIDADE = 'S') SM
                                                     ON SM.SEQPRODUTO = QP.SEQPRODUTO
                                    
;
